settings:

  # Value of the x coordinate
  # You can use _ (underscore) as thousands separator
  # This value is expected to be around 6_000_000
  value_x: 6_531_125

  # Value of the y coordinate
  # You can use _ (underscore) as thousands separator
  # This value is expected to be around 4_000_000
  value_y: 4_939_000

  # Standard frame border width (along x axis)
  frame_width_large: 375
  frame_width_small: 187.5

  # Standard frame border height (along y axis)
  frame_height_large: 250
  frame_height_small: 125

  # Layer name
  # MUST SURROUND WITH APOSTROPHES ' & '
  layer_name: 'OKVIR'

  # File name under which to save the dxf, in the local directory
  # MUST SURROUND WITH APOSTROPHES ' & '
  save_as_filename: 'frame.dxf'

  # Defines desired tick spacing (calculated automatically for the first tick)
  tick_spacing_large: 100
  tick_spacing_small: 50

  # Height/width of the tick mark,
  # measured from each axis (and then to up/down, and left/righ)
  tick_half_size: 0.5

  # Text heights
  text_height_small_frame: 1.0
  text_height_large_frame: 2.5

  # Line-to-line spacing
  line_to_line_spacing: 1.25

  # Axis-to-text spacing
  axis_to_text_spacing: 1.25

  # Do not change unless you know what you're doing!
  # Digit width as a (measured) ratio of digit height
  # (further divided by 2 in code)
  # ENTER VALUE AS A PERCENTAGE, E.G. 43 MEANS 43%
  digit_width_ratio: 43

  # Text alignment string, for x-axis labels
  x_text_alignment: TOP_LEFT

  # Text alignment string, for y-axis labels
  y_text_alignment: TOP_LEFT

  # DWG drawing standard string (see ezdxf documentation)
  dwg_standard: 'R2018'
